name: Tagged Release

on:
  push:
    tags:
      - 'release-[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish to WordPress plugin repository
    runs-on: ubuntu-latest
    steps:
    - name: TAG
      run : |
        export GTAG=$(echo $GITHUB_REF | sed -e "s/refs\/tags\/release-//g")
        echo "GTAG=$(printf '%q' $GTAG)" >> $GITHUB_ENV

    - name: SVN
      run : sudo apt-get install subversion

    - name: Prepare GIT Heckler
      uses: actions/checkout@v2
      with:
        ref: active
        path: git-heckler/

    - name: Prepare SVN Heckler
      run : |
        mkdir svn-heckler/
        svn co https://plugins.svn.wordpress.org/heckler svn-heckler

    - name: GIT → SVN
      run : |
        rm -r svn-heckler/assets/*
        rm -r svn-heckler/trunk/*

        cp -r git-heckler/assets/* svn-heckler/assets/
        cp -r git-heckler/plugin/* svn-heckler/trunk/

        sed "s/{{TAG}}/$GTAG/g" git-heckler/readme.tpl > svn-heckler/trunk/readme.txt
        cat svn-heckler/trunk/readme.txt

    - name: SVN → WordPress
      env :
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      run : |
        cd svn-heckler/

        svn add --force assets/* > /dev/null
        svn add --force trunk/* > /dev/null

        svn cp "trunk" "tags/$GTAG"

        svn commit -m "GIT → SVN [$GTAG]" --no-auth-cache --non-interactive --username "$SVN_USERNAME" --password "$SVN_PASSWORD"
